// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotaFiscal.Api.Context;

#nullable disable

namespace NotaFiscal.Api.Migrations
{
    [DbContext(typeof(NotaFiscalContext))]
    partial class NotaFiscalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Nota", b =>
                {
                    b.Property<int>("NotaFiscalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotaFiscalId"));

                    b.Property<string>("CnpjDestinatarioNf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjEmissorNf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNf")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroNf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("NotaFiscalId");

                    b.ToTable("NotasFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
